Repository samdoreee/FieldGeoLogAndroid, pull requests merged in 2022-11, with the labels that each got.

#3 basic gps tracking
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/samdoreee/fieldgeolog/MainActivity.kt
  app/src/main/jniLibs/arm64-v8a/libDaumMapEngineApi.so
  app/src/main/jniLibs/armeabi-v7a/libDaumMapEngineApi.so
  app/src/main/jniLibs/armeabi/libDaumMapEngineApi.so
  app/src/main/res/drawable-v24/custom_marker_red.png
  app/src/main/res/drawable-v24/custom_poi_marker.png
  app/src/main/res/drawable-v24/custom_poi_marker_end.png
  app/src/main/res/layout/main.xml
  build.gradle
  settings.gradle
Labels: enhancement

#4 서버와의 통신 기능 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/samdoreee/fieldgeolog/MainActivity.kt
  app/src/main/java/com/samdoreee/fieldgeolog/network/GeoApiService.kt
  app/src/main/java/com/samdoreee/fieldgeolog/network/Spot.kt
  app/src/main/java/com/samdoreee/fieldgeolog/network/SpotRequest.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/SpotApp.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/SpotViewModel.kt
  app/src/main/res/layout/main.xml
Labels: feature

#7 design: 어플 로고 및 타이틀 변경
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable-nodpi/samdoree.png
  app/src/main/res/mipmap-mdpi/samdoree_icon.png
  app/src/main/res/values/strings.xml
Labels: design
