Repository samdoreee/FieldGeoLogAndroid, pull requests merged in 2023-11, with the labels that each got.

#32 fix: 카카오맵 버전 업데이트
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/samdoreee/fieldgeolog/ui/activity/MainActivity.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/activity/NewRecordActivity.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/activity/OldNewRecordActivity.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_geo_map.xml
  app/src/main/res/layout/activity_main_community_list_item.xml
  app/src/main/res/layout/activity_main_my_record_list_item.xml
  app/src/main/res/layout/activity_new_record.xml
  app/src/main/res/layout/main.xml
  settings.gradle
Labels: fix

#33 feature: 기록 조회 기능 개발
  app/src/main/java/com/samdoreee/fieldgeolog/data/model/MyRecordModel.kt
  app/src/main/java/com/samdoreee/fieldgeolog/network/File.kt
  app/src/main/java/com/samdoreee/fieldgeolog/network/GeoApiService.kt
  app/src/main/java/com/samdoreee/fieldgeolog/network/Memo.kt
  app/src/main/java/com/samdoreee/fieldgeolog/network/PersonalRecordResponse.kt
  app/src/main/java/com/samdoreee/fieldgeolog/network/SpotResponse.kt
  app/src/main/java/com/samdoreee/fieldgeolog/network/UserResponse.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/activity/MainActivity.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/activity/MyRecordActivity.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/adapter/MainMyRecordRVAdapter.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/adapter/MyRecordAdapter.kt
Labels: feature

#35 feature: article 관련 부분 추가 연동 및 오류 수정
  app/src/main/java/com/samdoreee/fieldgeolog/S3FileDownloader.kt
  app/src/main/java/com/samdoreee/fieldgeolog/network/ArticleResponse.kt
Labels: feature

#37 Feature/36
  app/src/main/java/com/samdoreee/fieldgeolog/S3FileDownloader.kt
  app/src/main/java/com/samdoreee/fieldgeolog/data/model/CommunityModel.kt
  app/src/main/java/com/samdoreee/fieldgeolog/network/ArticleResponse.kt
  app/src/main/java/com/samdoreee/fieldgeolog/network/GeoApiService.kt
  app/src/main/java/com/samdoreee/fieldgeolog/network/PersonalRecordResponse.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/activity/CommunityActivity.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/activity/MainActivity.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/activity/MyRecordActivity.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/adapter/CommunityAdapter.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/adapter/MainCommunityAdapter.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/adapter/MainMyRecordRVAdapter.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/adapter/MyRecordAdapter.kt
  app/src/main/res/layout/activity_my_record.xml
Labels: feature

#40 fix: 기록 공유 열람 상세페이지 디자인 리뉴얼
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/samdoreee/fieldgeolog/data/model/CommentModel.kt
  app/src/main/java/com/samdoreee/fieldgeolog/data/model/OneRecordModel.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/activity/CommunityActivity.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/activity/MainActivity.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/activity/OneArticleActivity.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/activity/OneArticleDetailActivity.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/activity/OneRecordActivity.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/activity/OneRecordDetailActivity.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/activity/ReadPersonalRecordActivity.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/adapter/CommentRvAdapter.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/adapter/MainCommunityAdapter.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/adapter/OneArticleAdapter.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/adapter/OneRecordAdapter.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/adapter/SpotListRvAdapter.kt
  app/src/main/res/layout/activity_community_list_item.xml
  app/src/main/res/layout/activity_main_2.xml
  app/src/main/res/layout/activity_myrecord_list_item.xml
  app/src/main/res/layout/activity_new_record.xml
  app/src/main/res/layout/activity_one_article.xml
  app/src/main/res/layout/activity_one_article_detail.xml
  app/src/main/res/layout/activity_one_record.xml
  app/src/main/res/layout/activity_one_record_detail.xml
  app/src/main/res/layout/activity_read_article.xml
  app/src/main/res/layout/comment_item.xml
  app/src/main/res/layout/onerecorditem.xml
  app/src/main/res/layout/onespot_item.xml
Labels: fix

#43 fix: 나의 기록 열람 상세페이지 디자인 리뉴얼
  app/src/main/java/com/samdoreee/fieldgeolog/ui/activity/OneArticleActivity.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/activity/OneRecordActivity.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/activity/OneRecordDetailActivity.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/adapter/CommunitySpotListRvAdapter.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/adapter/MyRecordSpotListRvAdapter.kt
  app/src/main/res/layout/activity_one_record.xml
  app/src/main/res/layout/activity_one_record_detail.xml
  app/src/main/res/layout/comment_item.xml
Labels: fix

#44 feature: data model 관련 오류 해결 및 CommunityAdapter 클릭리스너 수정 완료(#42)
  app/src/main/java/com/samdoreee/fieldgeolog/network/FileResponse.kt
  app/src/main/java/com/samdoreee/fieldgeolog/network/SpotResponse.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/activity/CommunityActivity.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/activity/MainActivity.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/adapter/CommunityAdapter.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/adapter/MainCommunityAdapter.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/adapter/MainMyRecordRVAdapter.kt
  app/src/main/res/layout/activity_community.xml
Labels: bug

#46 feature: PersonalRecord 및 Article 조회 기능 구현 (#45)
  app/src/main/java/com/samdoreee/fieldgeolog/data/model/CommentModel.kt
  app/src/main/java/com/samdoreee/fieldgeolog/data/model/OneRecordModel.kt
  app/src/main/java/com/samdoreee/fieldgeolog/network/CommentResponse.kt
  app/src/main/java/com/samdoreee/fieldgeolog/network/GeoApiService.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/activity/CommunityActivity.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/activity/MainActivity.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/activity/MyRecordActivity.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/activity/OneArticleActivity.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/activity/OneArticleDetailActivity.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/activity/OneRecordActivity.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/activity/OneRecordDetailActivity.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/adapter/CommentRvAdapter.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/adapter/CommunitySpotListRvAdapter.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/adapter/MainMyRecordRVAdapter.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/adapter/MyRecordAdapter.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/adapter/MyRecordSpotListRvAdapter.kt
  app/src/main/res/layout/activity_one_article.xml
  app/src/main/res/layout/activity_one_record_detail.xml
Labels: feature

#49 feature: 기능 구현 등 (#47)
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/samdoreee/fieldgeolog/data/model/Constants.kt
  app/src/main/java/com/samdoreee/fieldgeolog/network/GeoApiService.kt
  app/src/main/java/com/samdoreee/fieldgeolog/network/PersonalRecordRequest.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/SpotApp.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/activity/MainActivity.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/activity/NewRecordActivity.kt
  app/src/main/java/com/samdoreee/fieldgeolog/ui/activity/WriteActivity.kt
  app/src/main/res/layout/activity_new_record.xml
Labels: feature
